#!/bin/sh
# Installed from an independently approved revision into an immutable store path.
set -eu
PATH='@PATH@'
export PATH
unset PYTHONHOME PYTHONPATH GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_NAMESPACE GIT_CONFIG_PARAMETERS
unset GIT_SSH_COMMAND GIT_SSH GIT_EXEC_PATH GIT_PROXY_COMMAND GIT_CONFIG_SYSTEM
unset GIT_COMMON_DIR GIT_OBJECT_DIRECTORY GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_SHALLOW_FILE GIT_GRAFT_FILE
unset GIT_REPLACE_REF_BASE GIT_CEILING_DIRECTORIES GIT_DISCOVERY_ACROSS_FILESYSTEM GH_CONFIG_DIR
unset GIT_EXTERNAL_DIFF GIT_DIFF_OPTS
unset TEMPLATES_SOURCE_BASE
GIT_CONFIG_COUNT=0
GIT_CONFIG_NOSYSTEM=1
GIT_CONFIG_GLOBAL=/dev/null
GIT_TERMINAL_PROMPT=0
GH_HOST=github.com
export GIT_CONFIG_COUNT GIT_CONFIG_NOSYSTEM GIT_CONFIG_GLOBAL GIT_TERMINAL_PROMPT GH_HOST
exec '@PYTHON@' -I '@PAYLOAD@' "$@"
